const formatMethod = {
    d: (date) => date.dayOfWeek,
    dd: (date) => date.localeData.dayNarrow[date.dayOfWeek],
    ddd: (date) => date.localeData.dayShort[date.dayOfWeek],
    dddd: (date) => date.localeData.dayLong[date.dayOfWeek],
    D: (date) => date.date,
    DD: (date) => `0${date.date}`.slice(-2),
    DDD: (date) => "",
    DDDD: (date) => "",
    E: (date) => date.dayOfWeek + 1,
    h: (date) => ((date.hour % 12) != 0) ? (date.hour % 12) : 12,
    hh: (date) => `0${((date.hour % 12) != 0) ? (date.hour % 12) : 12 || 12}`.slice(-2),
    H: (date) => date.hour,
    HH: (date) => `0${date.hour}`.slice(-2),
    m: (date) => date.minute,
    mm: (date) => `0${date.minute}`.slice(-2),
    mmm: (date) => `00${date.millisecond}`.slice(-3),
    M: (date) => date.month + 1,
    MM: (date) => `0${date.month + 1}`.slice(-2),
    MMM: (date) => date.localeData.monthShort[date.month],
    MMMM: (date) => date.localeData.monthLong[date.month],
    MMMMM: (date) => date.localeData.monthNarrow[date.month],
    s: (date) => date.second,
    ss: (date) => `0${date.second}`.slice(-2),
    sss: (date) => Math.floor((date - date.startOf("day")) / 1000),
    t: (date) => (date.hour < 12) ? "A" : "P",
    tt: (date) => (date.hour < 12) ? "AM" : "PM",
    TT: (date) => (date.year < 0) ? "BC" : "AD",
    yy: (date) => `0${date.year}`.slice(-2),
    yyyy: (date) => date.year,
    YY: (date) => `0${date.year}`.slice(-2),
    YYYY: (date) => date.year,
    L: (date) => date.format(date.localeData.shortDateFormat),
    LL: (date) => date.format(date.localeData.longDateFormat),
    LLL: (date) => date.format("dddd MMMM D YYYY"),
}
